### ISSUE TITLE
Security issue: Do not use /tmp/zypperoni

### ISSUE THREAD

**Issue by Vogtinator** [pavinjosdev/zypperoni#3]
`/tmp` is world-writable, which means that any unprivileged user can create and own `/tmp/zypperoni`.

zypperoni does not perform any verification and would use the foreign directory, which can lead to unprivileged users gaining root permissions.

I suggest using `/run/zypperoni` instead and also adding checks that it's in an expected state.

**Comment by pavinjosdev** [comment]
Hello @Vogtinator ,

Thank you for submitting this issue! 💯

I've pushed a patch to address this by securing zypperoni's temp dir on each invocation. 😅
I didn't want to move to `/run` dir as [distrobox](https://github.com/89luca89/distrobox) maps it into its containers.

**Comment by Vogtinator** [comment]
Your fix is vulnerable to a race condition: Someone might create the directory between `os.path.exists` and `mkdir -p`. If you really want to keep using `/tmp`, use `tempfile.TemporaryDirectory` or an equivalent that uses atomic directory creation with 0700 permissions.

**Comment by pavinjosdev** [comment]
@Vogtinator Indeed, there was a more pythonic way to create the temp dir, avoid race conditions and having to setup permissions manually. 🎉

Fixed in https://github.com/pavinjosdev/zypperoni/releases/tag/v0.3.1
