### ISSUE TITLE
zypperoni gives no error message whereas zypper says librpm.so.9 missing

### ISSUE THREAD

**Issue by as-muncher** [pavinjosdev/zypperoni#4]
My command is "zypperoni inr", no output, no error message, same thing when I enter "zypperoni dup".

If I enter "zypper", at least an error message shows up saying "zypper: error while loading shared libraries: librpm.so.9: cannot open shared object file: No such file or directory"

Maybe zypperoni should output something too in case of errors.

**Comment by pavinjosdev** [comment]
Hi there 👋

The debug flag should produce helpful output:
```
zypperoni --debug inr
```

**Comment by pavinjosdev** [comment]
@as-muncher Sorry about early closure, to my surprise the `--debug` option wasn't working as expected 🤦. This has been fixed and a warning has been added when zypperoni detects package conflicts requiring manual intervention. 🦎

Thanks for reporting this bug 🎉

**Comment by as-muncher** [comment]
@pavinjosdev You're welcome.  I think I ctrl-x'd the process when zypper dup was doing its thing, and then it wouldn't work properly, and a lot of processes wouldn't run, because librpm.so.9 or something like that wasn't working.  I had to use download an .iso with the latest version of openSUSE Tumbleweed, write it to a usb stick, then boot off that, and use the "upgrade" option to upgrade my system without a working zypper.

**Comment by pavinjosdev** [comment]
@as-muncher You may use my project [atomic-update](https://github.com/pavinjosdev/atomic-update) to prevent partial updates from rendering the system unusable. 🙂
